### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by aditirao7** [rottingresearch/rottingresearch#195]
It seems the website crashes while trying to analyze this PDF [sample.pdf](https://github.com/rottingresearch/rottingresearch/files/13292823/2206.00785.pdf). 
@marshalmiller can you paste a snippet of the logs here?

**Comment by marshalmiller** [comment]
@aditirao7 I'm sorry this took so long to get back to you. Here is the error from the logs.

```
`[2023-12-12 19:41:58,147] ERROR in app: Exception on / [POST]

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app

    response = self.full_dispatch_request()

               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request

    rv = self.handle_user_exception(e)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request

    rv = self.dispatch_request()

         ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "//app.py", line 117, in upload_pdf

    isCaptchaValid = validateCaptcha(request.form['g-recaptcha-response'])

                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "//app.py", line 189, in validateCaptcha

    'https://www.google.com/recaptcha/api/siteverify?secret='+app.config['CAPTCHA_SECRET_KEY']+'&response='+response).json()

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TypeError: can only concatenate str (not "NoneType") to str

172.21.0.1 - - [12/Dec/2023 19:41:58] "POST / HTTP/1.0" 500 -`
```

**Comment by marshalmiller** [comment]
This obviously was due to the new ENV variable and I don't think it was set properly in the live version. I have fixed this. Should be all good now.
